#  CI/CD Implementation

image: python:3.8

definitions:
  caches:
    rsync: /usr/bin/

pipelines:
  branches:
    master:
    - step:
        name: Copy to Server and Run
        deployment: production
        clone:
            enabled: true
        script:
            - pipe: atlassian/rsync-deploy:0.6.0
              variables:
                USER: $USER
                SERVER: $HOST
                REMOTE_PATH: $PROJECT_PATH
                LOCAL_PATH: './'
                DEBUG: 'true'
            - ssh $USER@$HOST "cd $PROJECT_PATH && sh bitbucket-deploy.sh && exit"
