"""added date to path, removed couple values

Revision ID: 201dc8a44e1b
Revises: 2d6185420033
Create Date: 2022-02-20 19:55:46.791344

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '201dc8a44e1b'
down_revision = '2d6185420033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('infection', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_infection_mandate_mask', table_name='infection')
    op.drop_column('infection', 'mandate_mask')
    op.add_column('infectioncondition', sa.Column('duration', sa.Float(), nullable=True))
    op.alter_column('infectioncondition', 'distance',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('infectioncondition', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ix_infectioncondition_duration'), 'infectioncondition', ['duration'], unique=False)
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.add_column('path', sa.Column('date', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False))
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ix_path_date'), 'path', ['date'], unique=False)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('infection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_path_date'), table_name='path')
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('path', 'date')
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_infectioncondition_duration'), table_name='infectioncondition')
    op.alter_column('infectioncondition', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('infectioncondition', 'distance',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('infectioncondition', 'duration')
    op.add_column('infection', sa.Column('mandate_mask', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_infection_mandate_mask', 'infection', ['mandate_mask'], unique=False)
    op.alter_column('infection', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('employee', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
