"""added infection conditions, chanred report referecnce to it

Revision ID: b156cdc98e58
Revises: debf0f040550
Create Date: 2022-02-20 19:32:09.082700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b156cdc98e58'
down_revision = 'debf0f040550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infectioncondition',
    sa.Column('mask_required', sa.Boolean(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('infection_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['infection_id'], ['infection.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infectioncondition_distance'), 'infectioncondition', ['distance'], unique=False)
    op.create_index(op.f('ix_infectioncondition_id'), 'infectioncondition', ['id'], unique=False)
    op.create_index(op.f('ix_infectioncondition_infection_id'), 'infectioncondition', ['infection_id'], unique=False)
    op.create_index(op.f('ix_infectioncondition_mask_required'), 'infectioncondition', ['mask_required'], unique=False)
    op.create_index(op.f('ix_infectioncondition_organization_id'), 'infectioncondition', ['organization_id'], unique=False)

    # Report 

    op.add_column('report', sa.Column('infection_condition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint('report_ibfk_2', 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'infectioncondition', ['infection_condition_id'], ['id'])
    op.drop_index('ix_report_infection_id', table_name='report')
    op.create_index(op.f('ix_report_infection_condition_id'), 'report', ['infection_condition_id'], unique=False)    
    op.drop_column('report', 'infection_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('infection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key('report_ibfk_2', 'report', 'infection', ['infection_id'], ['id'])
    op.drop_index(op.f('ix_report_infection_condition_id'), table_name='report')
    op.create_index('ix_report_infection_id', 'report', ['infection_id'], unique=False)
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('infection', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('employee', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_infectioncondition_organization_id'), table_name='infectioncondition')
    op.drop_index(op.f('ix_infectioncondition_mask_required'), table_name='infectioncondition')
    op.drop_index(op.f('ix_infectioncondition_infection_id'), table_name='infectioncondition')
    op.drop_index(op.f('ix_infectioncondition_id'), table_name='infectioncondition')
    op.drop_index(op.f('ix_infectioncondition_distance'), table_name='infectioncondition')
    op.drop_table('infectioncondition')
    # ### end Alembic commands ###
