"""add infection db

Revision ID: e8246e6bb0f2
Revises: ead1c6c4fce8
Create Date: 2021-11-23 11:54:33.633247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8246e6bb0f2'
down_revision = 'ead1c6c4fce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infection',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('mandate_mask', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infection_description'), 'infection', ['description'], unique=False)
    op.create_index(op.f('ix_infection_id'), 'infection', ['id'], unique=False)
    op.create_index(op.f('ix_infection_mandate_mask'), 'infection', ['mandate_mask'], unique=False)
    op.create_index(op.f('ix_infection_name'), 'infection', ['name'], unique=False)
    op.create_index(op.f('ix_infection_type'), 'infection', ['type'], unique=False)
    op.alter_column('employee', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('employee', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_infection_type'), table_name='infection')
    op.drop_index(op.f('ix_infection_name'), table_name='infection')
    op.drop_index(op.f('ix_infection_mandate_mask'), table_name='infection')
    op.drop_index(op.f('ix_infection_id'), table_name='infection')
    op.drop_index(op.f('ix_infection_description'), table_name='infection')
    op.drop_table('infection')
    # ### end Alembic commands ###
