"""add employee db

Revision ID: ead1c6c4fce8
Revises: bb64f8d96a35
Create Date: 2021-11-15 21:44:14.123883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead1c6c4fce8'
down_revision = 'bb64f8d96a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_first_name'), 'employee', ['first_name'], unique=False)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_organization_id'), 'employee', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_password'), 'employee', ['password'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('point', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('path', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('organization', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_password'), table_name='employee')
    op.drop_index(op.f('ix_employee_organization_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_first_name'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
